### ISSUE TITLE
KServe client cannot deserialize common Kubernetes objects

### ISSUE THREAD

**Issue by DorotheaKal** [kserve/kserve#2329] opened 2022-07-12 09:13 UTC
/kind bug

**What steps did you take and what happened:**
Deserializing a dictionary into a `V1beta1PredictorSpec` using the KServe client results in this error:
```
AttributeError: module 'kserve.models' has no attribute 'V1Container'
```
It turns out, the KServe client can't deserialize common Kubernetes objects like `V1Container`, as well as the other Kubernetes objects that the `V1beta1PredictorSpec` exposes.

The code we used is the following:
```
import kserve
from kserve import V1beta1PredictorSpec
predictor = {"activeDeadlineSeconds": 2, "containers": [{"name": "kserve-container"}]}
kserve.ApiClient()._ApiClient__deserialize(predictor, V1beta1PredictorSpec)
```

**What did you expect to happen:**
The KServe client to deserialize the dictionary into the `V1beta1PredictorSpec`.

**Anything else you would like to add:**
It seems that importing the Kubernetes objects that the `V1beta1PredictorSpec` uses in `kserve.models.__init__.py` could be a possible solution. The objects that should be imported are the following:
```
from kubernetes.client import V1Affinity
from kubernetes.client import V1Container
from kubernetes.client import V1PodDNSConfig
from kubernetes.client import V1EphemeralContainer
from kubernetes.client import V1HostAlias
from kubernetes.client import V1LocalObjectReference
from kubernetes.client import V1PodReadinessGate
from kubernetes.client import V1PodSecurityContext
from kubernetes.client import V1Toleration
from kubernetes.client import V1TopologySpreadConstraint
from kubernetes.client import V1Volume
```

**Environment:**

- KFServing Version: latest (built from master)

**Comment by KanwarGill811** [comment] 2023-09-14 18:06
### **In this comment the following functionalities shall be addressed as mentioned in the issue above #2329**
1.	The issue that the KServe client cannot deserialize common Kubernetes objects, and how it can be caused by various factors.
2.	To diagnose and potentially resolve deserialization issues with Kubernetes objects in KServe using Python.
3.	To figure out how KServe client can deserialize common Kubernetes objects like `V1Container,` as well as the other Kubernetes objects that the `V1beta1PredictorSpec` exposes.
4.	To configure how to Deserialize a dictionary into a `V1beta1PredictorSpec` using the KServe client


### **_Now the issue is that the KServe client cannot deserialize common Kubernetes objects, and this can be caused by various factors._**

So to troubleshoot and resolve this problem, we need to follow the below steps:
**_1.	Checking API Compatibility:_** It needs to be ensured that the KServe client version we are using is compatible with the Kubernetes cluster version we are targeting. Incompatibility can lead to deserialization issues.

**_2.	Kubernetes Object Version:_** Now we need to check if the Kubernetes objects we are trying to deserialize are using a Kubernetes API version that is supported by our KServe client or not. Kubernetes API versions can change between releases.

**_3.	Cluster Permissions:_** It needs to be ensured that the service account or user we are using to interact with the Kubernetes cluster has the necessary permissions to read the specific Kubernetes objects. Lack of permissions can lead to deserialization errors.

**_4.	Resource Definitions:_** It needs to be verified that the resource definitions for the Kubernetes objects we are trying to interact with are installed in the cluster. The KServe client may not be able to deserialize objects if their resource definitions are missing.

**_5.	KServe Configuration:_** The KServe configuration need to be reviewed properly to ensure it's correctly set up. Also we need to make sure we're using the appropriate configurations for the cluster and that they match the cluster's API server settings.

**_6.	Logs and Error Messages:_** It is important to check the logs and error messages from both the KServe client and the Kubernetes cluster. These messages can provide valuable information about the specific issue that's causing deserialization problems.

**_7.	KServe Client and API Changes:_** If the KServe client is recently upgraded or Kubernetes cluster, then there might be changes in the API or client behavior that affect deserialization. It is important to check for release notes or documentation related to the versions we are using.

**_8.	Custom Resources:_** If we're dealing with custom resources, ensure that the custom resource definitions (CRDs) are correctly installed in the cluster, and their versions match our client.

**_9.	Data Integrity:_** It is important to ensure that the data we are sending to the Kubernetes API is correctly formatted and does not contain any corruption. Data corruption can lead to deserialization issues.

**_10.	Networking and Firewalls:_** We need to also verify that there are no network issues or firewalls blocking communication between our KServe client and the Kubernetes API server. Network problems can lead to deserialization failures.

**_11.	Third-Party Plugins:_** If we're using third-party plugins or extensions with KServe, we need to check whether they are causing conflicts or deserialization issues. Disable them temporarily to see if the issue persists.

_By following these steps and carefully investigating the error messages and logs, we should be able to identify and resolve the issue with deserialization of common Kubernetes objects in our KServe client._

### **_Now to diagnose and potentially resolve deserialization issues with Kubernetes objects in KServe using Python, we can follow these technical steps:_**

**_1.	Check KServe and Kubernetes API Versions:_**

```
import kserve
from kubernetes import client as k8s_client
```

_# Check the KServe client version_

```
kserve_version = kserve.__version__
print("KServe Client Version:", kserve_version)
```

_# Check the Kubernetes API version_

```
k8s_api_version = k8s_client.VersionApi()
k8s_server_version = k8s_api_version.get_code()
print("Kubernetes Server Version:", k8s_server_version.git_version)
```

We need to Ensure that the KServe client version is compatible with the Kubernetes server version as stated in the code above

**_2.	Inspect Kubernetes Object API Versions:_**

`from kubernetes import client as k8s_client`

_# Specify the Kubernetes object you are having trouble with_

```
object_name = "your_object_name"
object_namespace = "your_object_namespace"
```

_# Create a Kubernetes API client_

```
k8s_api = k8s_client.CoreV1Api()

try:
    # Get the Kubernetes object
    k8s_object = k8s_api.read_namespaced_config_map(name=object_name, namespace=object_namespace)
    # Check the API version of the object
    object_api_version = k8s_object.api_version
    print(f"{object_name} API Version:", object_api_version)
except k8s_client.ApiException as e:
    print(f"Error getting {object_name}: {e}")
```

Now it is essential to ensure that the Kubernetes object we are trying to deserialize uses an API version that is supported by our KServe client. Using these steps we can systematically identify and address deserialization issues in our KServe client for Kubernetes objects.

### **_Now we need to figure out how KServe client can deserialize common Kubernetes objects like `V1Container`, as well as the other Kubernetes objects that the `V1beta1PredictorSpec` exposes_**

Now we know that KServe, is an open-source serving system for machine learning models, which typically doesn't require us to manually deserialize Kubernetes objects like `V1Container` or other Kubernetes resources. Instead, KServe provides high-level abstractions and APIs that allows us to define and deploy machine learning models without dealing with Kubernetes object deserialization directly.

_Here's how we can use KServe to deploy models using a `V1beta1PredictorSpec` without manually deserializing Kubernetes objects:_
_**•	Installing and Configuring KServe:**_ Firstly, we need to make sure that we have KServe installed and properly configured in our Kubernetes cluster. 
_**•	Defining our Model:**_ Creating or preparing our machine learning model and associated resources as needed. This could include model files, preprocessing and post-processing code, and any dependencies.
**_•	Defining a KServe Predictor:_** In KServe, we define a Predictor that specifies how to serve our model. We can create a YAML or JSON configuration file to define a Predictor, including the `V1beta1PredictorSpec`.

```
apiVersion: "serving.kserve.io/v1beta1"
kind: "Predictor"
metadata:
  name: "my-predictor"
spec:
  modelType: "tensorflow"
  modelName: "my-model"
  minReplicas: 1
  predictor:
    tensorflow:
      storageUri: "gs://my-model-bucket/my-model"
```

In the above code, we define a Predictor named "my-predictor" that uses a TensorFlow model stored in a Google Cloud Storage bucket.
**_•	Applying the Configuration:_** It is essential to apply the Predictor configuration to our Kubernetes cluster using `kubectl `or other deployment tools.

`kubectl apply -f predictor-config.yaml`

**_•	KServe Taking Care of Deserialization:_** KServe internally handles the deserialization of the `V1beta1PredictorSpec` and other Kubernetes objects for us. It translates our Predictor configuration into Kubernetes resources and manages the deployment and serving of our model.

**_•	Interacting with the Model:_** After our Predictor is deployed, we can interact with it by sending requests to its endpoint. KServe handles the inference process, including data preprocessing and model serving.


Here we define our serving configuration using KServe's high-level abstractions, and KServe takes care of the Kubernetes object management and deserialization internally.

### **_Now we need to configure how to Deserialize a dictionary into a `V1beta1PredictorSpec` using the KServe client_**

To deserialize a dictionary into a `V1beta1PredictorSpec` using the KServe client, we can use the Python Kubernetes client library (kubernetes package) to create the Kubernetes resource and then assign it to the spec field of the `V1beta1PredictorSpec`. Here's how we can do it step by step:

**_•	Importing Necessary Libraries:_**
Firstly, we need to make sure we have the kubernetes and kserve libraries installed. We can install them using pip:

`pip install kubernetes kserve`

**_Now the next step is importing the required modules:_**

```
from kubernetes import client, config
from kserve.api import KServeClient
from kserve.models import V1beta1PredictorSpec
```

**_•	Next step is to Load Kubernetes Configuration:_**

Load the Kubernetes configuration. If we're running our Python code outside the Kubernetes cluster, we'll typically need to specify the path to our kubeconfig file. If our code is running inside a Kubernetes pod, it can use the in-cluster configuration automatically.
		`config.load_kube_config(config_file='path_to_kubeconfig.yaml')`

**_•	Next step is to create a Kubernetes Object from the Dictionary:_**

Defining our dictionary representing the Kubernetes object (e.g., a ConfigMap) is important that we want to include in the `V1beta1PredictorSpec`.

```
# Sample dictionary representing a ConfigMap
config_map_dict = {
    "apiVersion": "v1",
    "kind": "ConfigMap",
    "metadata": {
        "name": "my-config-map",
        "namespace": "my-namespace"
    },
    "data": {
        "key1": "value1",
        "key2": "value2"
    }
}
```

**Now using the Kubernetes client to create the actual Kubernetes resource from the dictionary:**

```
k8s_api = client.CoreV1Api()
config_map = client.V1ConfigMap(**config_map_dict)
```

**_•	Creating a `V1beta1PredictorSpec` and Assigning the Kubernetes Object:_**

Now, we can create a `V1beta1PredictorSpec` and assign the Kubernetes resource to its value field. This assumes that we want to include the `ConfigMap` in our `PredictorSpec`.

```
predictor_spec = V1beta1PredictorSpec(
value=config_map
)
```

**_•	Using the `V1beta1PredictorSpec` in our Predictor Configuration:_**

**_Finally, using the predictor_spec in our Predictor configuration:_**

```
predictor = {
    "apiVersion": "serving.kserve.io/v1beta1",
    "kind": "Predictor",
    "metadata": {
        "name": "my-predictor"
    },
    "spec": {
        "modelType": "tensorflow",
        "modelName": "my-model",
        "predictor": predictor_spec
    }
}
```

_**•	Now we can deploy this Predictor configuration using the KServe client.**_

The above example demonstrates how to deserialize a dictionary into a `V1beta1PredictorSpec` and use it within a Predictor configuration. It must be made sure to adjust the dictionary and configuration as needed for our specific use case and Kubernetes resource type.

**Closed as completed** 2024-12-06 09:09 UTC
Labels: kind/bug, good first issue, kserve/sdk
