### ISSUE TITLE
Getting error from curl that "Model(tensorflow) with name model1 does not exist

### ISSUE THREAD

**Issue by tulsi0523** [kserve/kserve#1708] opened 2021-07-07 06:04 UTC
/kind bug

**What steps did you take and what happened:**
I have created inference service with kfserving client sdk v1alpha2 api

**What did you expect to happen:**
Url of inferenceservice with Ready as True

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment] 2021-07-07 12:35
@tulsi0523 Please provide with your inference service yaml.

**Comment by tulsi0523** [comment] 2021-07-07 14:54
@yuzisun 

I have created the inference service with client SDK. 

Below is code for same

from kubernetes import client

from kfserving import KFServingClient
from kfserving import constants
from kfserving import utils
from kfserving import V1alpha2EndpointSpec
from kfserving import V1alpha2PredictorSpec
from kfserving import V1alpha2TensorflowSpec
from kfserving import V1alpha2InferenceServiceSpec
from kfserving import V1alpha2InferenceService
from kubernetes.client import V1ResourceRequirements

namespace = utils.get_default_target_namespace()

api_version = constants.KFSERVING_GROUP + '/' + constants.KFSERVING_VERSION
# print(api_version)
default_endpoint_spec = V1alpha2EndpointSpec(
                          predictor=V1alpha2PredictorSpec(
                            sklearn=V1alpha2TensorflowSpec(
#                               storage_uri='s3a://logistic-regression/model_object',
                                storage_uri='pvc://saved_model',
                              resources=V1ResourceRequirements(
                                  requests={'cpu':'100m','memory':'1Gi'},
                                  limits={'cpu':'100m', 'memory':'1Gi'}))))
    
isvc = V1alpha2InferenceService(api_version=api_version,
                          kind=constants.KFSERVING_KIND,
                          metadata=client.V1ObjectMeta(
                              name='modelgru',namespace=namespace),
                          spec=V1alpha2InferenceServiceSpec(default=default_endpoint_spec))

KFServing = KFServingClient()

KFServing.create(isvc)

{'apiVersion': 'serving.kubeflow.org/v1alpha2',
 'kind': 'InferenceService',
 'metadata': {'creationTimestamp': '2021-07-06T09:35:11Z',
  'generation': 1,
  'managedFields': [{'apiVersion': 'serving.kubeflow.org/v1alpha2',
    'fieldsType': 'FieldsV1',
    'fieldsV1': {'f:spec': {'.': {},
      'f:default': {'.': {},
       'f:predictor': {'.': {},
        'f:sklearn': {'.': {},
         'f:resources': {'.': {},
          'f:limits': {'.': {}, 'f:cpu': {}, 'f:memory': {}},
          'f:requests': {'.': {}, 'f:cpu': {}, 'f:memory': {}}},
         'f:storageUri': {}}}}}},
    'manager': 'Swagger-Codegen',
    'operation': 'Update',
    'time': '2021-07-06T09:35:09Z'}],
  'name': 'modelgru',
  'namespace': 'abc',
  'resourceVersion': '67467038',
  'selfLink': '/apis/serving.kubeflow.org/v1alpha2/namespaces/kubeflow-user-example-com/inferenceservices/modelgru',
  'uid': 'b383655f-4621-462a-a85a-5624fc0afbf5'},
 'spec': {'default': {'predictor': {'sklearn': {'resources': {'limits': {'cpu': '100m',
       'memory': '1Gi'},
      'requests': {'cpu': '100m', 'memory': '1Gi'}},
     'runtimeVersion': 'd7a4462af7b84aaff9e0065908cd4bbf4db06941873bce83c487113f83be0f41',
     'storageUri': 'pvc://saved_model'}}}},
 'status': {}}


content of saved_model
5/
saved_model.pb
variables
assests

**Comment by yuzisun** [comment] 2023-04-09 17:22
Closing as the issue is too old.

**Closed by yuzisun** 2023-04-09 17:22 UTC
Labels: kind/bug, kfserving/tensorflow
