### ISSUE TITLE
Reframing CI/CD test to avoid running unrelated tests for each PR

### ISSUE THREAD

**Issue by jinchihe** [kserve/kserve#270] opened 2019-07-26 03:18 UTC
/kind feature

**Describe the solution you'd like**
For now, each PR will trigger long time CI/CD testing, in fact some of them are not related with the PR, for example if we changed files under pkg/api, that's not related the build images Stepes, those images sometime running timeout and failed, that waste time. Suggest to create a separated workflow for those testing by define reasonable prow file.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jinchihe** [comment] 2019-08-21 01:00
We need to take high priority to handle this, the CI/CD tests always failed for timeout or some other strange reasons.

**Comment by jinchihe** [comment] 2019-10-11 14:22
Need to enhance build steps to save CI test time.

**Comment by nm2107** [comment] 2020-01-08 10:25
Hello,
Maybe this tool can help you ? https://github.com/KnpLabs/should-skip-ci

**Comment by jinchihe** [comment] 2020-01-09 02:31
@nm2107 Thanks sharing, we need to inestigate how to integrate with current CI famerwork, and I think we need to consider when to skip or not, such as some dir is not changed etc...

**Comment by yuzisun** [comment] 2022-10-04 02:52
closing as the issue is staled and we have done so much improvements for the e2e infra

**Closed by yuzisun** 2022-10-04 02:52 UTC
Labels: area/docs, priority/p2, kind/feature
