### ISSUE TITLE
Smoke test of Kservee did not work when the previous step is running correctly

### ISSUE THREAD

**Issue by oyy2000** [kserve/kserve#2426] opened 2022-09-19 16:35 UTC
/kind bug
I wonder why the smoke test did not work when the previous step is running( the controller manager ).
**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

<img width="1450" alt="image" src="https://user-images.githubusercontent.com/56588848/191067592-f333ece0-0a74-4ed5-ad93-7ff58132b539.png">

**What did you expect to happen:**
![image](https://user-images.githubusercontent.com/56588848/191067937-811a911b-5a50-462d-9c53-9621a373a114.png)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment] 2022-09-22 01:54
@oyy2000 can you check the inference service yaml status instead of pods? There might be some setup issues why your pods is not coming up

**Comment by yuzisun** [comment] 2023-04-09 17:59
Closing as the issue is staled and most likely setup issue.

**Closed as completed by yuzisun** 2023-04-09 17:59 UTC
Labels: kind/bug
